amcl:
  ros__parameters:
    alpha1: 0.05
    alpha2: 0.05
    alpha3: 0.05
    alpha4: 0.05
    alpha5: 0.05
    base_frame_id: "base_link"
    global_frame_id: "map"
    odom_frame_id: "odom"
    laser_model_type: "likelihood_field"
    laser_likelihood_max_dist: 1.5
    max_beams: 40
    do_beamskip: false
    min_particles: 400
    max_particles: 1200
    pf_err: 0.02
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 2
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    update_min_a: 0.3 
    update_min_d: 0.35
    transform_tolerance: 0.5
    tf_broadcast: true
    z_hit: 0.7
    z_short: 0.05
    z_max: 0.05
    z_rand: 0.2
    sigma_hit: 0.3
    scan_topic: /scan
    map_topic: map
    set_initial_pose: true
    always_reset_initial_pose: false
    first_map_only: false
    initial_pose:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0


